version: "3.4"
services:
    influxdb:
        image: influxdb:1.8
        container_name: influxdb
        environment:
            - "INFLUXDB_DATA_INDEX_VERSION=tsi1"
        ports:
            - "8083:8083"
            - "8086:8086"

    php:
        container_name: "php"
        build:
            context: .
            dockerfile: ./php.dockerfile
            args:
                SWOOLE_DOCKER_VERSION: ${SWOOLE_DOCKER_VERSION}
        environment:
            - "INFLUXDB_HOST=influxdb"
        volumes:
            - "${GITHUB_WORKSPACE}:/app:rw"
        working_dir: /app
        ulimits:
            core: -1
        privileged: true
        command: tail -f /etc/group
