sudo: required
language: php
dist: trusty

php:
  - "7.1"
  - "7.2"
  - "7.3"
  - "7.4"

env:
  matrix:
  - INFLUXDB_VERSION=1.7.9
  global:
  - INFLUXDB_HOST=127.0.0.1
  - INFLUXDB_PORT=8086
  - INFLUXDB_USERNAME=
  - INFLUXDB_PASSWORD=
  - INFLUXDB_TEST_DB=db_influxdb_orm

install:
  - wget -O influxdb.deb https://dl.influxdata.com/influxdb/releases/influxdb_${INFLUXDB_VERSION}_amd64.deb
  - dpkg -i influxdb.deb
  - service influxdb start

before_script:
  - composer update

script:
  - composer test
