name: ci

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        php:
          [
            8.0,
            7.4,
            7.3,
            7.2,
            7.1
          ]

    env:
      PHP_DOCKER_VERSION: ${{ matrix.php }}

    steps:
      - uses: actions/checkout@v2

      - name: prepare
        run: |
          cd .github
          docker-compose up -d
          docker exec php composer update

      - name: test
        run: docker exec php composer test
