name: ci

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        swoole:
          [
            4.8-php8.1,
            4.8-php8.0,
            4.8-php7.4,
            4.8-php7.3,
            4.8-php7.2,
            4.5-php7.1,
          ]

    env:
      SWOOLE_DOCKER_VERSION: ${{ matrix.swoole }}

    steps:
      - uses: actions/checkout@v2

      - name: prepare
        run: |
          cd .github
          docker-compose up -d
          docker exec php composer update

      - name: test
        run: docker exec php composer test
